server:
  port: 8081

jero:
  swagger-open: true #是否开启swagger(true/false)
  release: localhost

spring:
  application:
    name: jero-file
    http:
      multipart:
        max-request-size: 100MB
        max-file-size: 100MB

druid:
  driverClassName: oracle.jdbc.driver.OracleDriver
  url: jdbc:oracle:thin:@//118.190.136.80:1521/orcl
  username: jero
  password: 123456

mybatis:
  type-aliases-package: com.lxt.file.entity #model包位置映射
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers:
      - com.lxt.core.util.JeroMapper
  not-empty: false
  identity: ORACLE
  before: true

pagehelper:
  helperDialect: oracle
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

fdfs:
  soTimeout: 1500
  connectTimeout: 600
  thumbImage:             #缩略图生成参数
    width: 150
    height: 150
  trackerList:            #TrackerList参数,支持多个
    - 47.97.19.73:22122